var animations = [
  {
    titre: "Belotte",
    date: "12/12/2012",
    animateur: "Alexandre",
    vote: 132,
    voteUp: 100,
    voteDown: 10,
    voteSoso: 22,
    salle: "salle de loisir",
    inscrits: [
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
    ],
    remarque: "Tout c'est très bien déroulé"
  },
  {
    titre: "Belotte",
    date: "12/12/2012",
    animateur: "Alexandre",
    salle: "salle de loisir",
    inscrits: [
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
    ],
    remarque: "Tout c'est très bien déroulé"
  },
  {
    titre: "Belotte",
    date: "12/12/2012",
    animateur: "Alexandre",
    salle: "salle de loisir",
    inscrits: [
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
    ],
    remarque: "Tout c'est très bien déroulé"
  },
  {
    titre: "Belotte",
    date: "12/12/2012",
    animateur: "Alexandre",
    salle: "salle de loisir",
    inscrits: [
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
    ],
    remarque: "Tout c'est très bien déroulé"
  },
  {
    titre: "Belotte",
    date: "12/12/2012",
    animateur: "Alexandre",
    salle: "salle de loisir",
    inscrits: [
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
    ],
    remarque: "Tout c'est très bien déroulé"
  },
  {
    titre: "Belotte",
    date: "12/12/2012",
    animateur: "Alexandre",
    salle: "salle de loisir",
    inscrits: [
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
    ],
    remarque: "Tout c'est très bien déroulé"
  },
  {
    titre: "Belotte",
    date: "12/12/2012",
    animateur: "Alexandre",
    salle: "salle de loisir",
    inscrits: [
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
    ],
    remarque: "Tout c'est très bien déroulé"
  },
  {
    titre: "Belotte",
    date: "12/12/2012",
    animateur: "Alexandre",
    salle: "salle de loisir",
    inscrits: [
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
    ],
    remarque: "Tout c'est très bien déroulé"
  },
  {
    titre: "Belotte",
    date: "12/12/2012",
    animateur: "Alexandre",
    salle: "salle de loisir",
    inscrits: [
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
    ],
    remarque: "Tout c'est très bien déroulé"
  },
  {
    titre: "Belotte",
    date: "12/12/2012",
    animateur: "Alexandre",
    salle: "salle de loisir",
    inscrits: [
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
    ],
    remarque: "Tout c'est très bien déroulé"
  },
  {
    titre: "Belotte",
    date: "12/12/2012",
    animateur: "Alexandre",
    salle: "salle de loisir",
    inscrits: [
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
    ],
    remarque: "Tout c'est très bien déroulé"
  },
  {
    titre: "Belotte",
    date: "12/12/2012",
    animateur: "Alexandre",
    salle: "salle de loisir",
    inscrits: [
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
    ],
    remarque: "Tout c'est très bien déroulé"
  },
  {
    titre: "Belotte",
    date: "12/12/2012",
    animateur: "Alexandre",
    salle: "salle de loisir",
    inscrits: [
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
    ],
    remarque: "Tout c'est très bien déroulé"
  },
  {
    titre: "Belotte",
    date: "12/12/2012",
    animateur: "Alexandre",
    salle: "salle de loisir",
    inscrits: [
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
    ],
    remarque: "Tout c'est très bien déroulé"
  },
  {
    titre: "Belotte",
    date: "12/12/2012",
    animateur: "Alexandre",
    salle: "salle de loisir",
    inscrits: [
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
    ],
    remarque: "Tout c'est très bien déroulé"
  },
  {
    titre: "Belotte",
    date: "12/12/2012",
    animateur: "Alexandre",
    salle: "salle de loisir",
    inscrits: [
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
    ],
    remarque: "Tout c'est très bien déroulé"
  },
  {
    titre: "Belotte",
    date: "12/12/2012",
    animateur: "Alexandre",
    salle: "salle de loisir",
    inscrits: [
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
    ],
    remarque: "Tout c'est très bien déroulé"
  },
  {
    titre: "Belotte",
    date: "12/12/2012",
    animateur: "Alexandre",
    salle: "salle de loisir",
    inscrits: [
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
      {nom: "Delaunay", prenom: "Marcelle", present: false},
    ],
    remarque: "Tout c'est très bien déroulé"
  },
]

export default animations
